services:
  - type: web
    name: mi-backend-render
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /