services:
  - type: web
    name: gest-proy-v2-back
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /